fix: no operational delete_files method (#7)
* fix: no operational delete_files method

* Added 'recursive' parameter to delete directory recursively as well.

* fix: use str (size in bytes) for Tus-Max-Size

Tus-Max-Size should be non-negative integer, but aiohttp requires
headers' values to be str.

max-upload-size is typed as BinarySize, but this raises following exception:

ERROR Unhandled exception
Traceback (most recent call last):
File
"/home/adrysn/.pyenv/versions/venv-master-storage-proxy/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 461, in start
await prepare_meth(request)
File
"/home/adrysn/.pyenv/versions/venv-master-storage-proxy/lib/python3.8/site-packages/aiohttp/web_response.py", line 353, in prepare
return await self._start(request)
File
"/home/adrysn/.pyenv/versions/venv-master-storage-proxy/lib/python3.8/site-packages/aiohttp/web_response.py", line 667, in _start
return await super()._start(request)
File
"/home/adrysn/.pyenv/versions/venv-master-storage-proxy/lib/python3.8/site-packages/aiohttp/web_response.py", line 410, in _start
await writer.write_headers(status_line, headers)
File
"/home/adrysn/.pyenv/versions/venv-master-storage-proxy/lib/python3.8/site-packages/aiohttp/http_writer.py", line 111, in write_headers
buf = _serialize_headers(status_line, headers)
File
"/home/adrysn/.pyenv/versions/venv-master-storage-proxy/lib/python3.8/site-packages/aiohttp/http_writer.py", line 160, in _py_serialize_headers
[k + ': ' + v + '\r\n' for k, v in headers.items()])
File
"/home/adrysn/.pyenv/versions/venv-master-storage-proxy/lib/python3.8/site-packages/aiohttp/http_writer.py", line 160, in <listcomp>
[k + ': ' + v + '\r\n' for k, v in headers.items()])
TypeError: can only concatenate str (not "BinarySize") to str

* fix: add archive parameter in download API

* refactor: remove t.Null for parameters with default value

* feat: add no_cache parameter to download a file with no-store cache control